# Generated by Django 2.2.5 on 2019-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LR_app', '0001_initial'),
        ('exam2', '0002_auto_20190923_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='users_going',
            field=models.ManyToManyField(related_name='user_traveling', to='LR_app.User'),
        ),
    ]
